const LANGUAGES = [
    { code: "ar", flag: "🇸🇦", name_ar: "العربية", name_en: "Arabic", popular: true },
    { code: "en", flag: "🇺🇸", name_ar: "الإنجليزية", name_en: "English", popular: true },
    { code: "fr", flag: "🇫🇷", name_ar: "الفرنسية", name_en: "French", popular: true },
    { code: "es", flag: "🇪🇸", name_ar: "الإسبانية", name_en: "Spanish", popular: true },
    { code: "de", flag: "🇩🇪", name_ar: "الألمانية", name_en: "German", popular: true },
    { code: "tr", flag: "🇹🇷", name_ar: "التركية", name_en: "Turkish", popular: true },
    { code: "ru", flag: "🇷🇺", name_ar: "الروسية", name_en: "Russian", popular: true },
    { code: "zh", flag: "🇨🇳", name_ar: "الصينية", name_en: "Chinese", popular: true },
    { code: "ja", flag: "🇯🇵", name_ar: "اليابانية", name_en: "Japanese", popular: true },
    { code: "ko", flag: "🇰🇷", name_ar: "الكورية", name_en: "Korean", popular: true },
    { code: "hi", flag: "🇮🇳", name_ar: "الهندية", name_en: "Hindi", popular: true },
    { code: "ur", flag: "🇵🇰", name_ar: "الأوردو", name_en: "Urdu", popular: true },
    { code: "fa", flag: "🇮🇷", name_ar: "الفارسية", name_en: "Persian", popular: true },
    { code: "pt", flag: "🇧🇷", name_ar: "البرتغالية", name_en: "Portuguese", popular: true },
    { code: "it", flag: "🇮🇹", name_ar: "الإيطالية", name_en: "Italian", popular: true },
    { code: "nl", flag: "🇳🇱", name_ar: "الهولندية", name_en: "Dutch" },
    { code: "pl", flag: "🇵🇱", name_ar: "البولندية", name_en: "Polish" },
    { code: "ro", flag: "🇷🇴", name_ar: "الرومانية", name_en: "Romanian" },
    { code: "uk", flag: "🇺🇦", name_ar: "الأوكرانية", name_en: "Ukrainian" },
    { code: "cs", flag: "🇨🇿", name_ar: "التشيكية", name_en: "Czech" },
    { code: "sk", flag: "🇸🇰", name_ar: "السلوفاكية", name_en: "Slovak" },
    { code: "hu", flag: "🇭🇺", name_ar: "المجرية", name_en: "Hungarian" },
    { code: "el", flag: "🇬🇷", name_ar: "اليونانية", name_en: "Greek" },
    { code: "bg", flag: "🇧🇬", name_ar: "البلغارية", name_en: "Bulgarian" },
    { code: "hr", flag: "🇭🇷", name_ar: "الكرواتية", name_en: "Croatian" },
    { code: "sr", flag: "🇷🇸", name_ar: "الصربية", name_en: "Serbian" },
    { code: "sl", flag: "🇸🇮", name_ar: "السلوفينية", name_en: "Slovenian" },
    { code: "fi", flag: "🇫🇮", name_ar: "الفنلندية", name_en: "Finnish" },
    { code: "sv", flag: "🇸🇪", name_ar: "السويدية", name_en: "Swedish" },
    { code: "da", flag: "🇩🇰", name_ar: "الدنماركية", name_en: "Danish" },
    { code: "nb", flag: "🇳🇴", name_ar: "النرويجية", name_en: "Norwegian" },
    { code: "th", flag: "🇹🇭", name_ar: "التايلاندية", name_en: "Thai" },
    { code: "vi", flag: "🇻🇳", name_ar: "الفيتنامية", name_en: "Vietnamese" },
    { code: "id", flag: "🇮🇩", name_ar: "الإندونيسية", name_en: "Indonesian" },
    { code: "ms", flag: "🇲🇾", name_ar: "الملايو", name_en: "Malay" },
    { code: "he", flag: "🇮🇱", name_ar: "العبرية", name_en: "Hebrew" },
    { code: "sw", flag: "🇰🇪", name_ar: "السواحلية", name_en: "Swahili" },
    { code: "bn", flag: "🇧🇩", name_ar: "البنغالية", name_en: "Bengali" },
    { code: "ta", flag: "🇮🇳", name_ar: "التاميلية", name_en: "Tamil" },
    { code: "te", flag: "🇮🇳", name_ar: "التيلوغو", name_en: "Telugu" },
    { code: "ml", flag: "🇮🇳", name_ar: "المالايالامية", name_en: "Malayalam" },
    { code: "mr", flag: "🇮🇳", name_ar: "الماراتية", name_en: "Marathi" },
    { code: "gu", flag: "🇮🇳", name_ar: "الغوجاراتية", name_en: "Gujarati" },
    { code: "kn", flag: "🇮🇳", name_ar: "الكانادا", name_en: "Kannada" },
    { code: "pa", flag: "🇮🇳", name_ar: "البنجابية", name_en: "Punjabi" },
    { code: "ar-EG", flag: "🇪🇬", name_ar: "العربية - مصر", name_en: "Arabic (EG)" },
    { code: "ar-AE", flag: "🇦🇪", name_ar: "العربية - الإمارات", name_en: "Arabic (AE)" },
    { code: "ar-MA", flag: "🇲🇦", name_ar: "العربية - المغرب", name_en: "Arabic (MA)" },
    { code: "en-GB", flag: "🇬🇧", name_ar: "الإنجليزية - بريطانيا", name_en: "English (UK)" },
    { code: "en-AU", flag: "🇦🇺", name_ar: "الإنجليزية - أستراليا", name_en: "English (AU)" },
    { code: "en-IN", flag: "🇮🇳", name_ar: "الإنجليزية - الهند", name_en: "English (IN)" },
    { code: "es-MX", flag: "🇲🇽", name_ar: "الإسبانية - المكسيك", name_en: "Spanish (MX)" },
    { code: "fr-CA", flag: "🇨🇦", name_ar: "الفرنسية - كندا", name_en: "French (CA)" },
    { code: "zh-TW", flag: "🇹🇼", name_ar: "الصينية - تايوان", name_en: "Chinese (TW)" },
    { code: "pt-PT", flag: "🇵🇹", name_ar: "البرتغالية - البرتغال", name_en: "Portuguese (PT)" },
    { code: "af", flag: "🇿🇦", name_ar: "الأفريكانية", name_en: "Afrikaans" },
    { code: "az", flag: "🇦🇿", name_ar: "الأذربيجانية", name_en: "Azerbaijani" },
    { code: "ka", flag: "🇬🇪", name_ar: "الجورجية", name_en: "Georgian" },
    { code: "hy", flag: "🇦🇲", name_ar: "الأرمينية", name_en: "Armenian" },
    { code: "is", flag: "🇮🇸", name_ar: "الأيسلندية", name_en: "Icelandic" },
    { code: "et", flag: "🇪🇪", name_ar: "الإستونية", name_en: "Estonian" },
    { code: "lv", flag: "🇱🇻", name_ar: "اللاتفية", name_en: "Latvian" },
    { code: "lt", flag: "🇱🇹", name_ar: "الليتوانية", name_en: "Lithuanian" },
    { code: "ca", flag: "🇪🇸", name_ar: "الكتالانية", name_en: "Catalan" },
    { code: "kk", flag: "🇰🇿", name_ar: "الكازاخية", name_en: "Kazakh" },
    { code: "uz", flag: "🇺🇿", name_ar: "الأوزبكية", name_en: "Uzbek" },
    { code: "mn", flag: "🇲🇳", name_ar: "المنغولية", name_en: "Mongolian" },
    { code: "ne", flag: "🇳🇵", name_ar: "النيبالية", name_en: "Nepali" },
    { code: "si", flag: "🇱🇰", name_ar: "السنهالية", name_en: "Sinhala" },
    { code: "my", flag: "🇲🇲", name_ar: "البورمية", name_en: "Burmese" },
    { code: "km", flag: "🇰🇭", name_ar: "الخميرية", name_en: "Khmer" },
    { code: "lo", flag: "🇱🇦", name_ar: "اللاوية", name_en: "Lao" },
    { code: "tl", flag: "🇵🇭", name_ar: "الفلبينية", name_en: "Filipino" },
    { code: "am", flag: "🇪🇹", name_ar: "الأمهرية", name_en: "Amharic" },
    { code: "so", flag: "🇸🇴", name_ar: "الصومالية", name_en: "Somali" },
    { code: "zu", flag: "🇿🇦", name_ar: "الزولو", name_en: "Zulu" },
    { code: "yo", flag: "🇳🇬", name_ar: "اليوروبا", name_en: "Yoruba" },
    { code: "ps", flag: "🇦🇫", name_ar: "البشتو", name_en: "Pashto" },
    { code: "or", flag: "🇮🇳", name_ar: "الأوديا", name_en: "Odia" },
];

if (typeof window !== 'undefined') window.LANGUAGES = LANGUAGES;
