// languages-data.js — بيانات اللغات المدعومة
window.LANGUAGES = [
    { code: 'ar',  name_ar: 'العربية',      name_en: 'Arabic',     flag: '🇸🇦', popular: true },
    { code: 'en',  name_ar: 'الإنجليزية',   name_en: 'English',    flag: '🇬🇧', popular: true },
    { code: 'es',  name_ar: 'الإسبانية',    name_en: 'Spanish',    flag: '🇪🇸', popular: true },
    { code: 'fr',  name_ar: 'الفرنسية',     name_en: 'French',     flag: '🇫🇷', popular: true },
    { code: 'de',  name_ar: 'الألمانية',    name_en: 'German',     flag: '🇩🇪', popular: true },
    { code: 'it',  name_ar: 'الإيطالية',    name_en: 'Italian',    flag: '🇮🇹', popular: true },
    { code: 'pt',  name_ar: 'البرتغالية',   name_en: 'Portuguese', flag: '🇵🇹', popular: true },
    { code: 'ru',  name_ar: 'الروسية',      name_en: 'Russian',    flag: '🇷🇺', popular: true },
    { code: 'tr',  name_ar: 'التركية',      name_en: 'Turkish',    flag: '🇹🇷', popular: true },
    { code: 'zh',  name_ar: 'الصينية',      name_en: 'Chinese',    flag: '🇨🇳', popular: true },
    { code: 'ja',  name_ar: 'اليابانية',    name_en: 'Japanese',   flag: '🇯🇵', popular: false },
    { code: 'ko',  name_ar: 'الكورية',      name_en: 'Korean',     flag: '🇰🇷', popular: false },
    { code: 'hi',  name_ar: 'الهندية',      name_en: 'Hindi',      flag: '🇮🇳', popular: false },
    { code: 'nl',  name_ar: 'الهولندية',    name_en: 'Dutch',      flag: '🇳🇱', popular: false },
    { code: 'sv',  name_ar: 'السويدية',     name_en: 'Swedish',    flag: '🇸🇪', popular: false },
    { code: 'pl',  name_ar: 'البولندية',    name_en: 'Polish',     flag: '🇵🇱', popular: false },
    { code: 'fa',  name_ar: 'الفارسية',     name_en: 'Persian',    flag: '🇮🇷', popular: false },
    { code: 'id',  name_ar: 'الإندونيسية',  name_en: 'Indonesian', flag: '🇮🇩', popular: false },
    { code: 'th',  name_ar: 'التايلندية',   name_en: 'Thai',       flag: '🇹🇭', popular: false },
    { code: 'vi',  name_ar: 'الفيتنامية',   name_en: 'Vietnamese', flag: '🇻🇳', popular: false },
    { code: 'uk',  name_ar: 'الأوكرانية',   name_en: 'Ukrainian',  flag: '🇺🇦', popular: false },
    { code: 'el',  name_ar: 'اليونانية',    name_en: 'Greek',      flag: '🇬🇷', popular: false },
    { code: 'cs',  name_ar: 'التشيكية',     name_en: 'Czech',      flag: '🇨🇿', popular: false },
    { code: 'ro',  name_ar: 'الرومانية',    name_en: 'Romanian',   flag: '🇷🇴', popular: false },
    { code: 'he',  name_ar: 'العبرية',      name_en: 'Hebrew',     flag: '🇮🇱', popular: false }
];
